/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edd;

import java.awt.Image;
import java.awt.Toolkit;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;
import poo.Archivos;

/**
 *
 * @author marip
 */
public class VtnAltas extends javax.swing.JFrame
{

    public static ListaDLC lc;
    private boolean nomrep;
    public static String[] arre;

    /**
     * Creates new form VtnAltas
     *
     */
    public VtnAltas()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo.png")));
        initComponents();
        this.setLocationRelativeTo(null);

        VtnPrincipal.disablepaste(priori);
        VtnPrincipal.disablepaste(nom);
        VtnPrincipal.disablepaste(quant);
    }

    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        priori = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        quant = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        aceptarB = new javax.swing.JButton();
        cancelarB = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel2.setText("Registro de Procesos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 190, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reg.png"))); // NOI18N
        jLabel4.setToolTipText("Regresar a Menú Principal");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel3.setText("No. Prioridad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 20));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, 20));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel5.setText("Quantums");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, 20));

        priori.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                prioriActionPerformed(evt);
            }
        });
        priori.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                prioriKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                prioriKeyTyped(evt);
            }
        });
        getContentPane().add(priori, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 150, -1));

        nom.setEnabled(false);
        nom.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nomActionPerformed(evt);
            }
        });
        nom.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                nomKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nomKeyTyped(evt);
            }
        });
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 150, -1));

        quant.setEnabled(false);
        quant.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                quantKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                quantKeyTyped(evt);
            }
        });
        getContentPane().add(quant, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 150, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alta.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        aceptarB.setBackground(new java.awt.Color(0, 0, 0));
        aceptarB.setFont(new java.awt.Font("Roboto Medium", 1, 11)); // NOI18N
        aceptarB.setForeground(new java.awt.Color(255, 255, 255));
        aceptarB.setText("Aceptar");
        aceptarB.setToolTipText("Guardar datos");
        aceptarB.setEnabled(false);
        aceptarB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aceptarBActionPerformed(evt);
            }
        });
        aceptarB.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                aceptarBKeyPressed(evt);
            }
        });
        getContentPane().add(aceptarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        cancelarB.setBackground(new java.awt.Color(0, 0, 0));
        cancelarB.setFont(new java.awt.Font("Roboto Medium", 1, 11)); // NOI18N
        cancelarB.setForeground(new java.awt.Color(255, 255, 255));
        cancelarB.setText("Cancelar");
        cancelarB.setToolTipText("Eliminar datos");
        cancelarB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelarBActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        fondo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel4MouseClicked
    {//GEN-HEADEREND:event_jLabel4MouseClicked
        new VtnPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void cancelarBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelarBActionPerformed
    {//GEN-HEADEREND:event_cancelarBActionPerformed
        CtrlInterfaz.limpia(nom, priori, quant);
        CtrlInterfaz.habilita(false, nom, quant);
        CtrlInterfaz.habilita(false, aceptarB);
        CtrlInterfaz.cambia(priori);
    }//GEN-LAST:event_cancelarBActionPerformed

    private void nomKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomKeyPressed
    {//GEN-HEADEREND:event_nomKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, nom, quant);
    }//GEN-LAST:event_nomKeyPressed

    private void nomKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomKeyTyped
    {//GEN-HEADEREND:event_nomKeyTyped
//        priori.setEnabled(false);
        Validaciones.validaAlfabeticos(evt, 20, nom.getText());
    }//GEN-LAST:event_nomKeyTyped

    private void prioriKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_prioriKeyPressed
    {//GEN-HEADEREND:event_prioriKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, priori, nom);

    }//GEN-LAST:event_prioriKeyPressed

    private void prioriKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_prioriKeyTyped
    {//GEN-HEADEREND:event_prioriKeyTyped
        Validaciones.validaEntero(evt, 2, priori.getText());
    }//GEN-LAST:event_prioriKeyTyped

    private void quantKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_quantKeyPressed
    {//GEN-HEADEREND:event_quantKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, quant, aceptarB);

    }//GEN-LAST:event_quantKeyPressed

    private void quantKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_quantKeyTyped
    {//GEN-HEADEREND:event_quantKeyTyped
        Validaciones.validaEntero(evt, 2, quant.getText());
    }//GEN-LAST:event_quantKeyTyped

    private void aceptarBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aceptarBActionPerformed
    {//GEN-HEADEREND:event_aceptarBActionPerformed
        try
        {

            if (Integer.valueOf(priori.getText()) == 0 || Integer.valueOf(quant.getText()) == 0)
            {
                Mensajes.error(this, "Los valores no pueden ser igual a 0");
                CtrlInterfaz.limpia(priori, quant, nom);
                CtrlInterfaz.cambia(priori);
            } else
            {
                Proceso proc = new Proceso(Integer.valueOf(priori.getText()), nom.getText(), Integer.valueOf(quant.getText()));
                lc = Manipulacion.inserta(proc, lc);
                arre = Manipulacion.insertaNom(arre, nom.getText());

                Archivos.guarda(this, arre, "Arre.dat");
                Archivos.guarda(this, lc, "Datos.dat");

                Mensajes.exito(this, "Datos guardados con éxito");
                CtrlInterfaz.limpia(priori, nom, quant);
                CtrlInterfaz.habilita(false, nom, quant, aceptarB);
                CtrlInterfaz.cambia(priori);
            }

        } catch (Exception e)
        {
            Mensajes.error(this, "Error: " + e.toString());
        }
    }//GEN-LAST:event_aceptarBActionPerformed

    private void aceptarBKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_aceptarBKeyPressed
    {//GEN-HEADEREND:event_aceptarBKeyPressed
        try
        {

            if (Integer.valueOf(priori.getText()) == 0 || Integer.valueOf(quant.getText()) == 0)
            {
                Mensajes.error(this, "Error... Revise los campos.");
                CtrlInterfaz.limpia(priori, quant, nom);
                CtrlInterfaz.cambia(priori);
            } else
            {
                Proceso proc = new Proceso(Integer.valueOf(priori.getText()), nom.getText(), Integer.valueOf(quant.getText()));
                lc = Manipulacion.inserta(proc, lc);
                arre = Manipulacion.insertaNom(arre, nom.getText());

                Archivos.guarda(this, arre, "Arre.dat");
                Archivos.guarda(this, lc, "Datos.dat");

                Mensajes.exito(this, "Datos guardados con éxito");
                CtrlInterfaz.limpia(priori, nom, quant);
                CtrlInterfaz.habilita(false, nom, quant, aceptarB);
                CtrlInterfaz.cambia(priori);
            }

        } catch (Exception e)
        {
            Mensajes.error(this, "Error: " + e.toString());
        }
    }//GEN-LAST:event_aceptarBKeyPressed

    private void nomActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nomActionPerformed
    {//GEN-HEADEREND:event_nomActionPerformed
        nomrep = Manipulacion.verifNR(arre, nom.getText());
        if (nomrep == true) //si se repite entonces manda un mensaje
        {
            Mensajes.error(this, "Nombre repetido. Ingrese un nombre diferente");
            CtrlInterfaz.limpia(nom);
            CtrlInterfaz.habilita(false, nom);
            CtrlInterfaz.cambia(nom);
        }
    }//GEN-LAST:event_nomActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        Archivos.guarda(this, arre, "Arre.dat");
        Archivos.guarda(this, lc, "Datos.dat");
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        arre = (String[]) Archivos.cargaArr(this, "Arre.dat");
        lc = (ListaDLC) Archivos.carga(this, "Datos.dat");
    }//GEN-LAST:event_formWindowOpened

    private void prioriActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_prioriActionPerformed
    {//GEN-HEADEREND:event_prioriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prioriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnAltas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarB;
    private javax.swing.JButton cancelarB;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField priori;
    private javax.swing.JTextField quant;
    // End of variables declaration//GEN-END:variables
}
