/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edd;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;
import java.awt.Image;
import java.awt.Toolkit;
import poo.Archivos;

/**
 *
 * @author marip
 */
public class VtnConsultas extends javax.swing.JFrame
{

    private boolean existePr;

    /**
     * Creates new form VtnConsultas
     */
    public VtnConsultas()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo.png")));
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel4 = new javax.swing.JLabel();
        priori = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCons = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reg.png"))); // NOI18N
        jLabel4.setToolTipText("Regresar a Menú Principal");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        priori.setToolTipText("Consultar procesos por no. de prioridad");
        priori.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                prioriActionPerformed(evt);
            }
        });
        priori.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                prioriKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                prioriKeyTyped(evt);
            }
        });
        getContentPane().add(priori, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 130, -1));

        jTableCons.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableCons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCons);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 490, 220));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel6.setText("No. Prioridad");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, 20));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        fondo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prioriKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_prioriKeyPressed
    {//GEN-HEADEREND:event_prioriKeyPressed

        Validaciones.enterCadenaNoVacia(this, evt, priori, null);

    }//GEN-LAST:event_prioriKeyPressed

    private void prioriKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_prioriKeyTyped
    {//GEN-HEADEREND:event_prioriKeyTyped
        Validaciones.validaEntero(evt, 2, priori.getText());
    }//GEN-LAST:event_prioriKeyTyped

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel4MouseClicked
    {//GEN-HEADEREND:event_jLabel4MouseClicked
        new VtnPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        VtnAltas.arre = (String[]) Archivos.cargaArr(this, "Arre.dat");
        VtnAltas.lc = (ListaDLC) Archivos.carga(this, "Datos.dat");
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void prioriActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_prioriActionPerformed
    {//GEN-HEADEREND:event_prioriActionPerformed
        try
        {
            if (VtnAltas.lc != null)
            {
                if (priori.getText().equals(""))
                {
                    Mensajes.error(this, "No se puede buscar un campo vacio ");
                    CtrlInterfaz.limpia(priori);
                    CtrlInterfaz.habilita(false, priori);
                    CtrlInterfaz.cambia(priori);
                } else
                {
                    existePr = Manipulacion.verifEP(VtnAltas.lc, Integer.parseInt(priori.getText()));

                    if (existePr == false)
                    {
                        Mensajes.error(this, "No existe la prioridad. Ingrese una prioridad diferente");
                        CtrlInterfaz.limpia(priori);
                        CtrlInterfaz.habilita(false, priori);
                        CtrlInterfaz.cambia(priori);
                    } else
                    {
                        Manipulacion.consultasTab(VtnAltas.lc, jTableCons, Integer.valueOf(priori.getText()));
                    }
                }

            } else
            {
                Mensajes.error(this, "No existen procesos registrados, ingresa primero datos");
                this.setVisible(false);
                new VtnAltas().setVisible(true);
            }

        } catch (Exception e)
        {
            Mensajes.error(this, "Error: " + e.toString());
        }


    }//GEN-LAST:event_prioriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnConsultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCons;
    private javax.swing.JTextField priori;
    // End of variables declaration//GEN-END:variables
}
